"""
Configuration parameters for the AI Trading Bot.
Contains all 50 parameters, constants, and global settings.
"""
import os
from dotenv import load_dotenv

load_dotenv()

# TRADING PAIRS
SYMBOLS = ["BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT"]
TIMEFRAME = "1h"
CANDLE_LIMIT = 500

# TREND PARAMETERS
MA_PERIOD = 20
EMA_FAST = 20
EMA_SLOW = 50
EMA_MAJOR = 200
WMA_PERIOD = 20
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
ADX_PERIOD = 14
ADX_TREND_THRESHOLD = 25
ICHIMOKU_TENKAN = 9
ICHIMOKU_KIJUN = 26
ICHIMOKU_SENKOU = 52

# MOMENTUM PARAMETERS
RSI_PERIOD = 14
RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 65
STOCH_K = 14
STOCH_D = 3
STOCH_SMOOTH = 3
WILLIAMS_R_PERIOD = 14
ROC_PERIOD = 12
CCI_PERIOD = 20
TSI_SLOW = 25
TSI_FAST = 13

# VOLATILITY PARAMETERS
BB_PERIOD = 20
BB_STD = 2
ATR_PERIOD = 14
KELTNER_PERIOD = 20
KELTNER_ATR_FACTOR = 2
DONCHIAN_PERIOD = 20

# VOLUME PARAMETERS
VOLUME_MA_PERIOD = 20
CMF_PERIOD = 20

# QUANT / MATH PARAMETERS
ZSCORE_PERIOD = 20
ZSCORE_BUY_THRESHOLD = -2.0
ZSCORE_SELL_THRESHOLD = +2.0
VOLATILITY_PERIOD = 20
HURST_LAG_MAX = 20
AUTOCORR_LAG = 1

# RISK MANAGEMENT
STOP_LOSS_ATR_MULT = 1.5
TAKE_PROFIT_ATR_MULT = 3.0
RISK_PER_TRADE_PCT = 0.02
MAX_OPEN_TRADES = 3
MAX_DRAWDOWN_PCT = 0.10
KELLY_FRACTION = 0.25

# AI / ML PARAMETERS
RF_N_ESTIMATORS = 200
RF_MAX_DEPTH = 10
LSTM_UNITS = 128
LSTM_DROPOUT = 0.2
LSTM_LOOKBACK = 60
LSTM_EPOCHS = 50
LSTM_BATCH_SIZE = 32
TRAIN_TEST_SPLIT = 0.80
RETRAIN_INTERVAL_HOURS = 24
MIN_SIGNAL_SCORE = 2.0  # Lowered from 4.0 to encourage more trades

# BOT BEHAVIOR
CHECK_INTERVAL_SECONDS = 60
TRADE_QUANTITY = 0.001
PAPER_BALANCE_USDT = 10000.0
DASHBOARD_PORT = int(os.getenv("DASHBOARD_PORT", 5000))

# ENVIRONMENT VARIABLES
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
BINANCE_SECRET_KEY = os.getenv("BINANCE_SECRET_KEY", "")
BINANCE_TESTNET = os.getenv("BINANCE_TESTNET", "True").lower() == "true"
PAPER_TRADING = os.getenv("PAPER_TRADING", "True").lower() == "true"
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
